version: '3.8'

services:
  app:
    build: .
    ports:
      - 4000:3000
    volumes:
      - ./public:/app/public
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - DB_DATABASE=database-name

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=database-name

volumes:
  postgres-data: